#listener configurations

listener.host: localhost
listener.port: 8081
listener.path: /path

#request configurations

request.host=training4-american-ws.cloudhub.io
request.port=80
request.path=/api/flights


